# Shell variables
# Generated by 'wal'
wallpaper='/home/xyrik/Downloads/742582.jpg'

# Special
background='#0E1012'
foreground='#aabfc4'
cursor='#aabfc4'

# Colors
color0='#0E1012'
color1='#344748'
color2='#1E5069'
color3='#545C57'
color4='#AF5E24'
color5='#DAAF3F'
color6='#316B93'
color7='#aabfc4'
color8='#768589'
color9='#344748'
color10='#1E5069'
color11='#545C57'
color12='#AF5E24'
color13='#DAAF3F'
color14='#316B93'
color15='#aabfc4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
