--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xyrik/Downloads/hanyijie_sky_scenery_ship_anime_art_104162_1920x1080.jpg"

-- Special
background="#192141"
foreground="#d4cdcc"
cursor="#d4cdcc"

-- Colors
color0="#192141"
color1="#53689C"
color2="#4778C2"
color3="#A47D84"
color4="#3E81BD"
color5="#5D87B7"
color6="#5D92CA"
color7="#d4cdcc"
color8="#948f8e"
color9="#53689C"
color10="#4778C2"
color11="#A47D84"
color12="#3E81BD"
color13="#5D87B7"
color14="#5D92CA"
color15="#d4cdcc"
