# Shell variables
# Generated by 'wal'
wallpaper='/home/xyrik/Downloads/hanyijie_sky_scenery_ship_anime_art_104162_1920x1080.jpg'

# Special
background='#192141'
foreground='#d4cdcc'
cursor='#d4cdcc'

# Colors
color0='#192141'
color1='#53689C'
color2='#4778C2'
color3='#A47D84'
color4='#3E81BD'
color5='#5D87B7'
color6='#5D92CA'
color7='#d4cdcc'
color8='#948f8e'
color9='#53689C'
color10='#4778C2'
color11='#A47D84'
color12='#3E81BD'
color13='#5D87B7'
color14='#5D92CA'
color15='#d4cdcc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
